from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, Form):
        Form.setObjectName("Form")
        Form.resize(628, 424)
        Form.setMinimumSize(QtCore.QSize(628, 424))
        Form.setMaximumSize(QtCore.QSize(628, 424))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        Form.setFont(font)
        Form.setMouseTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setStyleSheet("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelThree = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.labelThree.setFont(font)
        self.labelThree.setStyleSheet("")
        self.labelThree.setObjectName("labelThree")
        self.gridLayout_2.addWidget(self.labelThree, 2, 1, 1, 1)
        self.listConvrt = QtWidgets.QListWidget(Form)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.listConvrt.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.listConvrt.setFont(font)
        self.listConvrt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listConvrt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listConvrt.setObjectName("listConvrt")
        self.gridLayout_2.addWidget(self.listConvrt, 1, 1, 1, 1)
        self.labelOne = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.labelOne.setFont(font)
        self.labelOne.setStyleSheet("")
        self.labelOne.setObjectName("labelOne")
        self.gridLayout_2.addWidget(self.labelOne, 0, 0, 1, 1)
        self.labelTwo = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.labelTwo.setFont(font)
        self.labelTwo.setStyleSheet("")
        self.labelTwo.setObjectName("labelTwo")
        self.gridLayout_2.addWidget(self.labelTwo, 0, 1, 1, 1)
        self.usersConvrt = QtWidgets.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.usersConvrt.setFont(font)
        self.usersConvrt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.usersConvrt.setObjectName("usersConvrt")
        self.gridLayout_2.addWidget(self.usersConvrt, 1, 0, 3, 1)
        self.fieldInfo = QtWidgets.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.fieldInfo.setFont(font)
        self.fieldInfo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fieldInfo.setObjectName("fieldInfo")
        self.gridLayout_2.addWidget(self.fieldInfo, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.show()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Server"))
        self.labelThree.setText(_translate("Form", "---Information field---"))
        self.labelOne.setText(_translate("Form", "---Users conversation---"))
        self.labelTwo.setText(_translate("Form", "---List of conversations---"))

    def printInfo(self, info):
        self.fieldInfo.setText(str(info))
